library(ape)
args = commandArgs(trailingOnly=TRUE)

#This script is used to get samples from log file that is generated by MCMC
#The samples are obtained within a fixed foot step, i.e. size of M

treefile.folder <- args[1] 
output.txt.folder  <- args[2]

#treefile.folder <- "~/Desktop/validation/well_calibrated/" 
#output.txt.folder  <- "~/Desktop/validation/well_calibrated/output/" 

# get M samples in log file
# in log file, there 10001 states
#from 101-th state, a sample is obtained after every 100 states
M <- matrix(nrow = 100, ncol = 1)
j <- 1;
for(i in seq(1001, 2000, 10)) {
  M[j] = i;
  j = j + 1;
}

Taxon <- c(20,120)
for (taxa in Taxon) {
#read the log file
  L = read.nexus(file=paste0(treefile.folder,"simSeq_",taxa,"taxa.trees"))
  Tree = c()
  j=1;
  for (i in M) {
    Tree[j] = write.tree(L[[i]]);
    j = j + 1;
  }
  
  write.table(Tree,file=paste0(output.txt.folder,taxa,"taxa/trees.txt"),col.name=F,row.names=F,quote = F)
}
