
args = commandArgs(trailingOnly=TRUE)

#This script is used to get samples from log file that is generated by MCMC
#The samples are obtained within a fixed foot step, i.e. size of M

logfile.folder <- args[1] 
output.txt.folder  <- args[2]

#logfile.folder <- "~/validation/calibrated/priors/" 
#output.txt.folder  <- "~/validation/calibrated/true/" 


Taxa = c(20,120)
for (taxa in Taxa) {
#read the log file
L <- read.table(file=paste0(logfile.folder,"simSeq_",taxa,"taxa.log"), sep="\t", header=T)


# get M samples in log file
# in log file, there 10001 states
#from 101-th state, a sample is obtained after every 100 states
M=matrix(nrow = 100, ncol = 1)
j=1;
for(i in seq(1001, 2000, 10)) {
  M[j]=i;
  j=j+1;
}


A=L$BirthRate;
B=L$kappa;
C=L$ucldStdev;

#birthrates
I=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  I[j]=A[i];
  j=j+1;
}
write.table(I,file=paste0(output.txt.folder,taxa,"taxa/Bir.txt"),col.name=F,row.names=F)

#kappa
K=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  K[j]=B[i];
  j=j+1;
}
write.table(K,file=paste0(output.txt.folder,taxa,"taxa/Kap.txt"),col.name=F,row.names=F)
#ucld
U=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  U[j]=C[i];
  j=j+1;
}
write.table(U,file=paste0(output.txt.folder,taxa,"taxa/Ucld.txt"),col.name=F,row.names=F)


#Frequencies
F1=L$freqParameter.1
F2=L$freqParameter.2
F3=L$freqParameter.3
F4=L$freqParameter.4

#(1) save 4 frequency parameters into 4 seperate files
S1=matrix(nrow = 100, ncol = 1)
S2=matrix(nrow = 100, ncol = 1)
S3=matrix(nrow = 100, ncol = 1)
S4=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  S1[j]=F1[i];
  S2[j]=F2[i];
  S3[j]=F3[i];
  S4[j]=F4[i];
  j=j+1;
}
write.table(S1,file=paste0(output.txt.folder,taxa,"taxa/Freq1.txt"),col.name=F,row.names=F)
write.table(S2,file=paste0(output.txt.folder,taxa,"taxa/Freq2.txt"),col.name=F,row.names=F)
write.table(S3,file=paste0(output.txt.folder,taxa,"taxa/Freq3.txt"),col.name=F,row.names=F)
write.table(S4,file=paste0(output.txt.folder,taxa,"taxa/Freq4.txt"),col.name=F,row.names=F)
#(2) save 4 frequency parameters into one single file
#S=matrix(nrow = 100, ncol = 4)
#j=1;
#for (i in 1:100) {
#S[j,1]=S1[i];
#S[j,2]=S2[i];
#S[j,3]=S3[i];
#S[j,4]=S4[i];
#j=j+1;
#}
S=cbind(S1,S2,S3,S4)
write.table(S,file=paste0(output.txt.folder,taxa,"taxa/Freq.txt"),col.name=F,row.names=F)

#BranchRates
#get the mean of the rates
R=L$rate.mean
RatM=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  RatM[j]=R[i];
  j=j+1;
}
write.table(RatM,file=paste0(output.txt.folder,taxa,"taxa/RatM.txt"),col.name=F,row.names=F)

#Tree statistics
D=L$Tree.height
E=L$Tree.treeLength

TreH=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  TreH[j]=D[i];
  j=j+1;
}
write.table(TreH,file=paste0(output.txt.folder,taxa,"taxa/TreH.txt"),col.name=F,row.names=F)

TreL=matrix(nrow = 100, ncol = 1)
j=1;
for (i in M) {
  TreL[j]=E[i];
  j=j+1;
}
write.table(TreL,file=paste0(output.txt.folder,taxa,"taxa/TreL.txt"),col.name=F,row.names=F)
}
